### ISSUE TITLE
Cannot find table when wrapped with <p></p> unless in quirks mode.

### ISSUE THREAD

**Issue by EclipseKnight** [colinaut/action-table#10]
Error `Could not find table with thead and tbody in action-table
    at y.connectedCallback (action-table.js:1:2910)
    at action-table.js:1:9079`

I stumbled upon an interesting behavior when attempting to change from quirks mode (doctype not declared) to non quirks mode (!doctype html).
```html

<p>
   <table>
   </table>
</p>
```

Based on Mozilla documentation is may be caused due to implicit opening and closing:

>Tag soup parsing. For example, if a document contains the markup ```<p>text<table>...</table>``` then e.g. Firefox treats, in Quirks Mode, the p element as containing the table element. In Standards Mode, the start tag of table implicitly closes the open p element. The difference can be seen if you e.g. set a border on the p element. Similarly, for example, Firefox accepts a ul element inside a font element. IE always works by wrong rules in such issues, even in Standards Mode, but standards-conforming behavior can be achieved by using valid markup and always using explicit end tags like ```</p>``` even when they are formally optional.

This behavior is seen across chrome, mozilla, and opera (chromium). The solution is to simply not use `<p></p>` such as div. 

Just found the behavior interesting and thought I'd bring it to your attention!

**Comment by colinaut** [comment]
Oddly, I just tested this myself, in both Arc (Chromium) and Firefox, and did not see this at all. It found the table fine in both quirks and standard mode when it was wrapped in a p tag. Honestly can't see why it wouldn't since the part that throws the error is pretty simple js which shouldn't be bothered by what it is wrapped in:

```
const table = this.querySelector("table");

if (table && table.querySelector("thead tr th") && table.querySelector("tbody tr td")) {
  ...do stuff
} else {
  throw new Error("Could not find table with thead and tbody in action-table");
}
```

Maybe your table did not have thead with th and tbody with td? This component requires that.

Anyways, not that it matters much since yeah wrapping a table in a p is against the html spec. Thanks for bringing it up though. I'm gonna close this issue as not reproducible and not really a bug. If you discover something else about this issue feel free to comment on this even if it is closed, as I'll read it.
